### ISSUE TITLE
Parsing character names assumes all characters have 2 names

### ISSUE THREAD

**Issue by SoCariEVE** [MonoliYoda/evve_dashboard_dev#1]
`dashboard/views.py` tries to destructure a character's name into `first_name` and `last_name`. This fails for characters that have only one name.

**Comment by MonoliYoda** [comment]
Wrapping the `.split()` function in a try-catch block with a failover to `last_name ="" ` should do the trick.

**Comment by MonoliYoda** [comment]
I pushed this change to the dev server. If it works all good, will update the repo.

**Comment by dgrif** [comment]
tested with my main and alt, both single word usernames. prior to the fix I got the server error, but now it works. 👍

**Comment by MonoliYoda** [comment]
Fixed.
