### ISSUE TITLE
Opening UTF-8 encoded `.json` files fails for OSes where UTF-8 is not default (Windows)

### ISSUE THREAD

**Issue by SoCariEVE** [MonoliYoda/evve_dashboard_dev#15]
For example: `dashboard/utils.py:16` we call `open('invTypes.json', 'r')`

We need to add the `encoding` param to force the file to be read as UTF-8:

`open('invTypes.json', 'r', encoding='utf-8')`

**Comment by MonoliYoda** [comment]
The app no longer uses .json files, issue solved.
